{{- if not (or (and .Values.proxy.enabled .Values.service.jina.enabled) .Values.service.ovms.enabled) }}
{{- fail "at least one service endpoint must be enabled" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reranker.fullname" . }}
  labels:
    {{- include "reranker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "reranker.selectorLabels" . | nindent 4 }}
  ports:
    {{- if and .Values.proxy.enabled .Values.service.jina.enabled }}
    - name: jina-http
      port: {{ .Values.service.jina.port }}
      targetPort: proxy-http
      protocol: TCP
    {{- end }}
    {{- if .Values.service.ovms.enabled }}
    - name: ovms-http
      port: {{ .Values.service.ovms.port }}
      targetPort: ovms-http
      protocol: TCP
    {{- end }}
