apiVersion: v2
name: whoami
description: Helm chart for whoami, a tiny HTTP server that prints OS info and HTTP request details
type: application
version: 0.1.3
# renovate: datasource=docker depName=traefik/whoami
appVersion: "v1.11.0"
home: https://github.com/traefik/whoami
icon: https://www.gravatar.com/avatar/27caca9bcd7fd7f7412ca5255c9ae2d0?s=120&r=g&d=404
sources:
  - https://github.com/traefik/whoami
  - https://github.com/m11s-io/charts
maintainers:
  - name: m11s
    url: https://m11s.io
annotations:
  artifacthub.io/signKey: |
    fingerprint: 6C1DF3F0731DDD4E9047086F039223E48A6FF51F
    url: https://keys.openpgp.org/search?q=hello%40m11s.io
