{{- if .Values.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shlink.fullname" . }}
  labels:
    {{- include "shlink.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.data.size }}
  {{- with .Values.data.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
