apiVersion: v2
name: fider
description: Helm chart for Fider self-hosted user feedback platform
type: application
version: 0.3.5
# renovate: datasource=docker depName=getfider/fider
appVersion: "v0.35.0"
home: https://fider.io
icon: https://raw.githubusercontent.com/getfider/fider/main/favicon.png
sources:
  - https://github.com/getfider/fider
  - https://github.com/m11s-io/charts
maintainers:
  - name: m11s
    url: https://m11s.io
annotations:
  artifacthub.io/signKey: |
    fingerprint: 6C1DF3F0731DDD4E9047086F039223E48A6FF51F
    url: https://keys.openpgp.org/search?q=hello%40m11s.io
