apiVersion: v2
name: ovms
description: Deploy OpenVINO Model Server for any supported task
type: application
version: 0.2.1
appVersion: "2026.3.1"
home: https://github.com/m11s-io/helm-charts/tree/main/charts/ovms
icon: https://cdn-avatars.huggingface.co/v1/production/uploads/1671615670447-6346651be2dcb5422bcd13dd.png
sources:
  - https://github.com/openvinotoolkit/model_server
  - https://huggingface.co/OpenVINO
maintainers:
  - name: m11s
    url: https://github.com/m11s-io
annotations:
  artifacthub.io/license: Apache-2.0
