{{- if and .Values.valkey.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "searxng.fullname" . }}-valkey
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "searxng.selectorLabels" . | nindent 14 }}
      ports:
        - port: 6379
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: valkey
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - port: 6379
          protocol: TCP
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
